// <auto-generated />
using System;
using ClassSchedule.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClassSchedule.Migrations
{
    [DbContext(typeof(ClassScheduleDbContext))]
    [Migration("20200311105930_InitialMigration2")]
    partial class InitialMigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("ClassSchedule.Entities.Class", b =>
                {
                    b.Property<Guid>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Introduction")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("ClassId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = new Guid("8dec0933-6842-497b-a04e-c20ea7a86707"),
                            Introduction = "This is Class 1.",
                            Name = "Class1"
                        },
                        new
                        {
                            ClassId = new Guid("b4fef31c-9ab7-438c-ae83-68d9c03a241f"),
                            Introduction = "This is Class 1.",
                            Name = "Class1"
                        },
                        new
                        {
                            ClassId = new Guid("d0a8c12f-ad9c-41ee-b537-5acbeac653f1"),
                            Introduction = "This is Class 1.",
                            Name = "Class1"
                        },
                        new
                        {
                            ClassId = new Guid("01aec6ed-53a9-4281-8864-a3456b7443ad"),
                            Introduction = "This is Class 1.",
                            Name = "Class1"
                        },
                        new
                        {
                            ClassId = new Guid("181be1ec-eee9-41c0-8957-383c8e18ec38"),
                            Introduction = "This is Class 1.",
                            Name = "Class1"
                        });
                });

            modelBuilder.Entity("ClassSchedule.Entities.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BeginWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int>("EndWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lesson")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SingleOrDouble")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<int>("WeekDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ClassSchedule.Entities.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.HasKey("StudentId");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ClassSchedule.Entities.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<Guid>("ClassId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserName");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserName = "admin",
                            ClassId = new Guid("e4d182b4-bde0-4c59-95e0-9522c05b4a08"),
                            Password = "123456",
                            StudentId = new Guid("de70865f-6cb9-4dd2-8d88-d81324824131")
                        },
                        new
                        {
                            UserName = "test1",
                            ClassId = new Guid("05082016-cdf9-4f29-af4a-e8da6fa6452d"),
                            Password = "test1",
                            StudentId = new Guid("37c3cb75-9dc8-4b41-b472-282347f6433b")
                        },
                        new
                        {
                            UserName = "test2",
                            ClassId = new Guid("41ef3e75-63e0-485e-8c8a-c7d420a2c8e6"),
                            Password = "test2",
                            StudentId = new Guid("0738175f-022a-4d72-97f4-4fc6e1b58ac5")
                        });
                });

            modelBuilder.Entity("ClassSchedule.Entities.Course", b =>
                {
                    b.HasOne("ClassSchedule.Entities.Student", "Student")
                        .WithMany("Courses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassSchedule.Entities.Student", b =>
                {
                    b.HasOne("ClassSchedule.Entities.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
