// <auto-generated />
using System;
using ClassSchedule.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClassSchedule.Migrations
{
    [DbContext(typeof(ClassScheduleDbContext))]
    [Migration("20200313003004_InitialMigration3")]
    partial class InitialMigration3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("ClassSchedule.Entities.Class", b =>
                {
                    b.Property<Guid>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("Introduction")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.HasKey("ClassId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = new Guid("9433d145-5f42-4e4a-9ba4-0748fff8e6e6"),
                            ClassName = "Class1",
                            Introduction = "This is Class 1."
                        },
                        new
                        {
                            ClassId = new Guid("4c4b5936-6842-4bc2-a050-f633510fa7de"),
                            ClassName = "Class2",
                            Introduction = "This is Class 2."
                        },
                        new
                        {
                            ClassId = new Guid("10ef6ade-875f-421f-a405-e40decd2651c"),
                            ClassName = "Class3",
                            Introduction = "This is Class 3."
                        },
                        new
                        {
                            ClassId = new Guid("25648edb-ef72-42d2-bb66-11b7a4e9a17b"),
                            ClassName = "Class4",
                            Introduction = "This is Class 4."
                        },
                        new
                        {
                            ClassId = new Guid("cb38a446-b030-4ff9-94b6-d4cc7803a84e"),
                            ClassName = "Class5",
                            Introduction = "This is Class 5."
                        });
                });

            modelBuilder.Entity("ClassSchedule.Entities.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BeginWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int>("EndWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lesson")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SingleOrDouble")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<int>("WeekDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ClassSchedule.Entities.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.HasKey("StudentId");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ClassSchedule.Entities.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<Guid>("ClassId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserName");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserName = "admin",
                            ClassId = new Guid("b8395db5-d633-4d0d-beb5-62e8446f1d8b"),
                            Password = "123456",
                            StudentId = new Guid("fe4e3aeb-8772-42f3-acd7-81303a7522d5")
                        },
                        new
                        {
                            UserName = "test1",
                            ClassId = new Guid("a0994120-8d5e-4db5-befa-039793f2cd20"),
                            Password = "test1",
                            StudentId = new Guid("7c52bd70-ab30-48f1-860d-6df711b71fb8")
                        },
                        new
                        {
                            UserName = "test2",
                            ClassId = new Guid("6fce4416-93ff-47ff-b274-8581f3823979"),
                            Password = "test2",
                            StudentId = new Guid("5ae0ff83-5b80-46f1-975a-f7256ead77dc")
                        });
                });

            modelBuilder.Entity("ClassSchedule.Entities.Course", b =>
                {
                    b.HasOne("ClassSchedule.Entities.Student", "Student")
                        .WithMany("Courses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassSchedule.Entities.Student", b =>
                {
                    b.HasOne("ClassSchedule.Entities.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
