@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json

###
OPTIONS {{host}}/api/classes HTTP/1.1

###
GET {{host}}/api/classes HTTP/1.1

###
@classId_GET = 1b7b249e-658e-4ce5-a012-6277060e1a97
GET {{host}}/api/classes/{{classId_GET}} HTTP/1.1

###
POST {{host}}/api/classes HTTP/1.1
Content-Type: {{contentType}}

{
    "className": "Test Class",
    "introduction": "A Simple Class"
}

###
@classId_PUT = f08302a6-fd70-43a8-9000-ddae1daf1337
PUT {{host}}/api/classes/{{classId_PUT}} HTTP/1.1
Content-Type: {{contentType}}

{
    "className": "Test Class",
    "introduction": "A Simple Class"
}

###
@classId_PATCH = 3c2cef2a-0c6e-4990-a53c-7e614aae8f60
PATCH {{host}}/api/classes/{{classId_PATCH}} HTTP/1.1
Content-Type: {{contentType}}

[
    {
        "op": "replace",
        "path": "/className",
        "value": "Test Replace Class"
    }
]

###
@classId_DELETE = 3c2cef2a-0c6e-4990-a53c-7e614aae8f60
DELETE {{host}}/api/classes/{{classId_DELETE}} HTTP/1.1