@hostname = http://localhost
@port = 5000
@contentType = application/json
# (Guid) classId
@classId = 0000-0000-0000-0000
@studentId = 0000-0000-0000-0000
@route = api/classes/{classId}/students/{{studentId}}
@host = {{hostname}}:{{port}}/{{route}}

###
OPTIONS {{host}}/courses HTTP/1.1

###
GET {{host}}/courses HTTP/1.1

###
@courseId_GET = 0000
GET {{host}}/courses/{{courseId_GET}} HTTP/1.1

###
POST {{host}}/courses HTTP/1.1
Content-Type: {{contentType}}

{
    
}